"""PDF report generator for NetSentinel using reportlab."""
import io
from datetime import datetime
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    HRFlowable, Image, PageBreak, Paragraph, SimpleDocTemplate,
    Spacer, Table, TableStyle,
)
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.piecharts import Pie

# ── Palette ──────────────────────────────────────────────────────────────────
BG          = colors.HexColor('#010804')
CARD        = colors.HexColor('#061510')
ACCENT      = colors.HexColor('#00ff6e')
ACCENT2     = colors.HexColor('#10b981')
TEXT        = colors.HexColor('#dfffed')
TEXT_MUTED  = colors.HexColor('#5ea87a')
C_CRITICAL  = colors.HexColor('#ff3344')
C_HIGH      = colors.HexColor('#ff8800')
C_MEDIUM    = colors.HexColor('#ffc300')
C_LOW       = colors.HexColor('#00ff6e')
C_INFO      = colors.HexColor('#00ccff')
WHITE       = colors.white

LOGO_PATH = Path(__file__).parent / 'logo.png'

SEVERITY_COLORS = {
    'critical': C_CRITICAL,
    'high':     C_HIGH,
    'medium':   C_MEDIUM,
    'low':      C_LOW,
    'info':     C_INFO,
}

SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info']


def _grade_color(grade: str) -> colors.Color:
    return {'A': C_LOW, 'B': ACCENT2, 'C': C_MEDIUM, 'D': C_HIGH, 'F': C_CRITICAL}.get(grade, TEXT_MUTED)


def _styles():
    base = getSampleStyleSheet()
    def s(name, **kw):
        defaults = dict(fontName='Helvetica', fontSize=10, textColor=TEXT, leading=14)
        defaults.update(kw)
        return ParagraphStyle(name, **defaults)
    return {
        'h1':      s('h1', fontSize=26, fontName='Helvetica-Bold', textColor=ACCENT, leading=32, spaceAfter=4),
        'h2':      s('h2', fontSize=16, fontName='Helvetica-Bold', textColor=ACCENT, leading=22, spaceBefore=14, spaceAfter=6),
        'h3':      s('h3', fontSize=12, fontName='Helvetica-Bold', textColor=TEXT, leading=16, spaceBefore=8, spaceAfter=4),
        'body':    s('body', fontSize=9.5, textColor=TEXT, leading=14),
        'muted':   s('muted', fontSize=9, textColor=TEXT_MUTED, leading=12),
        'center':  s('center', alignment=TA_CENTER, fontSize=10, textColor=TEXT),
        'bullet':  s('bullet', fontSize=9.5, textColor=TEXT, leading=14, leftIndent=12, bulletIndent=0),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    # Header bar
    canvas.setFillColor(CARD)
    canvas.rect(0, h - 28*mm, w, 28*mm, fill=1, stroke=0)
    # Logo in header
    if LOGO_PATH.exists():
        canvas.drawImage(str(LOGO_PATH), 18*mm, h - 22*mm, width=14*mm, height=14*mm,
                         preserveAspectRatio=True, mask='auto')
    canvas.setFont('Helvetica-Bold', 11)
    canvas.setFillColor(ACCENT)
    canvas.drawString(36*mm, h - 14*mm, 'NetSentinel')
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(36*mm, h - 20*mm, 'Security Audit Report')
    # Page number
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawRightString(w - 18*mm, h - 16*mm, f'Page {doc.page}')
    # Footer line
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(0.5)
    canvas.line(18*mm, 14*mm, w - 18*mm, 14*mm)
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(18*mm, 10*mm, 'Confidential — Generated by NetSentinel')
    canvas.drawRightString(w - 18*mm, 10*mm, datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'))
    canvas.restoreState()


def _cover(scan: dict, st: dict, narrative: Optional[str]) -> list:
    scores  = scan.get('scores') or {}
    summary = scan.get('summary') or {}
    by_sev  = summary.get('by_severity') or {}
    grade   = scores.get('grade', 'N/A')
    overall = scores.get('weighted_overall', 0)
    target  = scan.get('target') or 'N/A'
    host    = scan.get('host') or 'N/A'
    date    = (scan.get('completed_at') or '')[:10]
    total   = summary.get('total_findings', 0)

    story = []

    # Logo
    if LOGO_PATH.exists():
        img = Image(str(LOGO_PATH), width=60, height=60)
        img.hAlign = 'LEFT'
        story.append(img)
        story.append(Spacer(1, 8*mm))

    story.append(Paragraph('Security Audit Report', st['h1']))
    story.append(HRFlowable(width='100%', thickness=1, color=ACCENT, spaceAfter=6))

    # Meta table
    meta = [
        ['Target', target],
        ['Host', host],
        ['Scan Date', date],
        ['Scan ID', scan.get('scan_id', 'N/A')[:16] + '...'],
        ['Duration', f"{scan.get('duration_seconds', 0):.1f}s"],
    ]
    t = Table(meta, colWidths=[45*mm, 120*mm])
    t.setStyle(TableStyle([
        ('FONTNAME',  (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE',  (0,0), (-1,-1), 9.5),
        ('FONTNAME',  (0,0), (0,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (-1,-1), TEXT),
        ('TEXTCOLOR', (0,0), (0,-1), TEXT_MUTED),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [CARD, colors.HexColor('#030f07')]),
        ('TOPPADDING',    (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING',   (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.3, colors.HexColor('#1a3a2a')),
        ('ROUNDEDCORNERS', [4]),
    ]))
    story.append(t)
    story.append(Spacer(1, 8*mm))

    # Grade + score highlight
    grade_col = _grade_color(grade)
    score_data = [
        [Paragraph(f'<font color="#{grade_col.hexval()[2:]}"><b>{grade}</b></font>', st['center']),
         Paragraph(f'<font color="#{ACCENT.hexval()[2:]}"><b>{overall:.0f}</b></font>', st['center']),
         Paragraph(f'<b>{total}</b>', st['center'])],
        [Paragraph('Grade', st['muted']), Paragraph('Overall /100', st['muted']), Paragraph('Total Findings', st['muted'])],
    ]
    score_t = Table(score_data, colWidths=[55*mm, 55*mm, 55*mm])
    score_t.setStyle(TableStyle([
        ('FONTNAME',  (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE',  (0,0), (-1,0), 28),
        ('FONTSIZE',  (0,1), (-1,1), 9),
        ('ALIGN',     (0,0), (-1,-1), 'CENTER'),
        ('VALIGN',    (0,0), (-1,-1), 'MIDDLE'),
        ('BACKGROUND',(0,0), (-1,-1), CARD),
        ('GRID',      (0,0), (-1,-1), 0.3, colors.HexColor('#1a3a2a')),
        ('TOPPADDING',    (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('ROUNDEDCORNERS', [4]),
    ]))
    story.append(score_t)
    story.append(Spacer(1, 8*mm))

    # Severity summary row
    sev_row = []
    for s in SEVERITY_ORDER:
        cnt = by_sev.get(s, 0)
        col = SEVERITY_COLORS[s]
        sev_row.append(Paragraph(
            f'<font color="#{col.hexval()[2:]}"><b>{cnt}</b></font><br/>'
            f'<font color="#{TEXT_MUTED.hexval()[2:]}" size="8">{s.upper()}</font>',
            st['center']
        ))
    sev_t = Table([sev_row], colWidths=[33*mm]*5)
    sev_t.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('BACKGROUND', (0,0), (-1,-1), CARD),
        ('GRID', (0,0), (-1,-1), 0.3, colors.HexColor('#1a3a2a')),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('FONTSIZE', (0,0), (-1,-1), 14),
        ('ROUNDEDCORNERS', [4]),
    ]))
    story.append(sev_t)
    story.append(PageBreak())

    # Executive summary
    if narrative:
        story.append(Paragraph('Executive Summary', st['h2']))
        story.append(HRFlowable(width='100%', thickness=0.5, color=ACCENT, spaceAfter=6))
        for para in narrative.split('\n'):
            para = para.strip()
            if not para:
                story.append(Spacer(1, 3*mm))
            elif para.startswith('**') and para.endswith('**'):
                story.append(Paragraph(para.strip('*'), st['h3']))
            elif para.startswith('- ') or para.startswith('* '):
                story.append(Paragraph(f'• {para[2:]}', st['bullet']))
            elif para[0].isdigit() and para[1] in '.':
                story.append(Paragraph(para, st['bullet']))
            else:
                story.append(Paragraph(para, st['body']))
        story.append(PageBreak())

    return story


def _domain_bar_chart(scores: dict) -> Drawing:
    domains = ['Network', 'TLS', 'HTTP', 'DNS']
    vals = [scores.get('network', 0), scores.get('tls', 0),
            scores.get('http', 0), scores.get('dns', 0)]
    benchmarks = [68, 72, 65, 70]

    d = Drawing(165*mm, 70*mm)
    chart = VerticalBarChart()
    chart.x, chart.y, chart.width, chart.height = 20*mm, 10*mm, 140*mm, 52*mm
    chart.data = [vals, benchmarks]
    chart.categoryAxis.categoryNames = domains
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = 100
    chart.valueAxis.valueStep = 20
    chart.bars[0].fillColor = ACCENT
    chart.bars[1].fillColor = colors.HexColor('#1a3a2a')
    chart.groupSpacing = 8
    chart.barSpacing = 2
    chart.categoryAxis.labels.fontName = 'Helvetica'
    chart.categoryAxis.labels.fontSize = 8
    chart.categoryAxis.labels.fillColor = TEXT_MUTED
    chart.valueAxis.labels.fontName = 'Helvetica'
    chart.valueAxis.labels.fontSize = 7
    chart.valueAxis.labels.fillColor = TEXT_MUTED
    chart.valueAxis.gridStrokeDashArray = [2, 4]
    chart.valueAxis.gridStrokeColor = colors.HexColor('#1a3a2a')
    d.add(chart)
    # Legend
    d.add(Rect(20*mm, 2*mm, 6*mm, 4*mm, fillColor=ACCENT, strokeColor=None))
    d.add(String(28*mm, 3*mm, 'This Scan', fontSize=7, fillColor=TEXT_MUTED, fontName='Helvetica'))
    d.add(Rect(55*mm, 2*mm, 6*mm, 4*mm, fillColor=colors.HexColor('#1a3a2a'), strokeColor=ACCENT2))
    d.add(String(63*mm, 3*mm, 'Industry Avg', fontSize=7, fillColor=TEXT_MUTED, fontName='Helvetica'))
    return d


def _severity_pie(by_sev: dict) -> Drawing:
    labels = [s for s in SEVERITY_ORDER if by_sev.get(s, 0) > 0]
    vals   = [by_sev[s] for s in labels]
    if not vals:
        return Drawing(80*mm, 60*mm)
    d = Drawing(80*mm, 70*mm)
    pie = Pie()
    pie.x, pie.y, pie.width, pie.height = 10*mm, 8*mm, 55*mm, 55*mm
    pie.data = vals
    pie.labels = [f'{l.upper()}\n{v}' for l, v in zip(labels, vals)]
    for i, sev in enumerate(labels):
        pie.slices[i].fillColor = SEVERITY_COLORS[sev]
        pie.slices[i].strokeColor = BG
        pie.slices[i].strokeWidth = 1
    pie.slices.labelRadius = 1.2
    pie.slices.fontSize = 6
    pie.slices.fontColor = TEXT_MUTED
    pie.slices.fontName = 'Helvetica'
    d.add(pie)
    return d


def _findings_table(findings: list, st: dict) -> list:
    story = []
    story.append(Paragraph('Findings', st['h2']))
    story.append(HRFlowable(width='100%', thickness=0.5, color=ACCENT, spaceAfter=6))

    sorted_findings = sorted(
        [f for f in findings if isinstance(f, dict)],
        key=lambda f: SEVERITY_ORDER.index(f.get('severity', 'info').lower())
        if f.get('severity', 'info').lower() in SEVERITY_ORDER else 99
    )

    headers = [
        Paragraph('#', st['muted']),
        Paragraph('Severity', st['muted']),
        Paragraph('Title', st['muted']),
        Paragraph('Domain', st['muted']),
        Paragraph('CVSS', st['muted']),
    ]
    rows = [headers]
    for i, f in enumerate(sorted_findings[:50], 1):
        sev = f.get('severity', 'info').lower()
        col = SEVERITY_COLORS.get(sev, TEXT_MUTED)
        rows.append([
            Paragraph(str(i), st['body']),
            Paragraph(f'<font color="#{col.hexval()[2:]}">{sev.upper()}</font>', st['body']),
            Paragraph(f.get('title', 'N/A')[:60], st['body']),
            Paragraph(f.get('domain', 'N/A'), st['body']),
            Paragraph(str(f.get('cvss_score', '–')), st['body']),
        ])

    if len(rows) > 1:
        col_w = [10*mm, 22*mm, 90*mm, 22*mm, 16*mm]
        t = Table(rows, colWidths=col_w, repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND',  (0,0), (-1,0), CARD),
            ('FONTNAME',    (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE',    (0,0), (-1,-1), 8.5),
            ('TEXTCOLOR',   (0,0), (-1,-1), TEXT),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#030f07'), BG]),
            ('GRID',        (0,0), (-1,-1), 0.3, colors.HexColor('#1a3a2a')),
            ('TOPPADDING',    (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING',   (0,0), (-1,-1), 6),
            ('VALIGN',      (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(t)
    else:
        story.append(Paragraph('No findings recorded.', st['muted']))

    return story


def generate_pdf(scan: dict, narrative: Optional[str] = None) -> bytes:
    """Generate PDF report and return raw bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm,
        topMargin=34*mm, bottomMargin=22*mm,
    )
    st = _styles()
    story = []

    # Cover + executive summary
    story.extend(_cover(scan, st, narrative))

    # Domain scores section
    scores = scan.get('scores') or {}
    story.append(Paragraph('Domain Scores vs Industry Benchmark', st['h2']))
    story.append(HRFlowable(width='100%', thickness=0.5, color=ACCENT, spaceAfter=6))

    by_sev = (scan.get('summary') or {}).get('by_severity') or {}
    charts_row = Table(
        [[_domain_bar_chart(scores), _severity_pie(by_sev)]],
        colWidths=[170*mm, 90*mm],
    )
    charts_row.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(charts_row)
    story.append(Spacer(1, 6*mm))

    # Domain score detail table
    domain_data = [
        [Paragraph(h, st['muted']) for h in ['Domain', 'Score', 'Grade', 'Benchmark', 'vs Avg']],
    ]
    benchmarks = {'Network': 68, 'TLS': 72, 'HTTP': 65, 'DNS': 70}
    for domain, key, bm in [('Network','network',68),('TLS','tls',72),('HTTP','http',65),('DNS','dns',70)]:
        val = scores.get(key, 0)
        diff = val - bm
        col = ACCENT if diff >= 0 else C_HIGH
        g = 'A' if val >= 90 else 'B' if val >= 80 else 'C' if val >= 70 else 'D' if val >= 60 else 'F'
        domain_data.append([
            Paragraph(domain, st['body']),
            Paragraph(f'<b>{val}</b>', st['body']),
            Paragraph(f'<font color="#{_grade_color(g).hexval()[2:]}">{g}</font>', st['body']),
            Paragraph(str(bm), st['body']),
            Paragraph(f'<font color="#{col.hexval()[2:]}">{("+" if diff>=0 else "")}{diff}</font>', st['body']),
        ])
    dt = Table(domain_data, colWidths=[35*mm,25*mm,20*mm,30*mm,30*mm])
    dt.setStyle(TableStyle([
        ('BACKGROUND',  (0,0), (-1,0), CARD),
        ('FONTNAME',    (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',    (0,0), (-1,-1), 9),
        ('TEXTCOLOR',   (0,0), (-1,-1), TEXT),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#030f07'), BG]),
        ('GRID',        (0,0), (-1,-1), 0.3, colors.HexColor('#1a3a2a')),
        ('TOPPADDING',    (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING',   (0,0), (-1,-1), 6),
    ]))
    story.append(dt)
    story.append(PageBreak())

    # Findings
    story.extend(_findings_table(scan.get('findings', []), st))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
